package com.rra.local_mission_management.enums;

public enum Status {
    SUBMITTED_FOR_APPROVAL,
    APPROVED,
    MISSION_ORDER_RETURNED,
    MISSION_ORDER_REJECTED,
    MISSION_ORDER_CLEARANCE_RECORD_CANCELLED,
    MISSION_COMPUTED,
    MISSION_PAYMENT_BATCH_CREATED,
    REPORTED,
    MISSION_REPORT_ACCEPTED,
    CLAIM_SUBMITTED,
    MISSION_REPORT_CANCELLED,
    MISSION_COMPUTATION_CANCELLED
}